In [4]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [9]:
## your code
# в числителе двойки возводятся в степень и делятся на знаменатель от 1 до 20
((2 * np.ones(20)) ** np.arange(1, 21)) / np.arange(1, 21)

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [13]:
## your code
# sum складывает значения вектора
((0.1**(3*np.arange(6)))*(0.2**(4*np.arange(6)))).sum()

1.00000160000256

**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [27]:
## your code
matrix = np.zeros((8, 8), int)
matrix[::2, ::2] = 1
matrix[::-2, ::-2] = 1
matrix

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [38]:
X = np.random.random((5, 2))

## your code
ro = np.sqrt(X[:, 0]**2 + X[:, 1]**2)
fi = np.arctan(X.T[1] / X.T[0])
polarCoordinates = np.array([ro, fi]).T
polarCoordinates

array([[0.57436296, 0.32187023],
       [0.59126267, 0.40026647],
       [0.82877216, 1.35503534],
       [1.02507386, 0.46854943],
       [0.88107029, 0.41250611]])

**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [71]:
X = np.random.random((10, 10))

## your code
# argmax возвращает число, в котором в первом разряде первая координата максимума в массиве, во втором - вторая
print(X)
maximumIndexes = np.argmax(X)
indexes = (maximumIndexes//10, maximumIndexes - (maximumIndexes//10)*10)
print(indexes)

[[0.17993825 0.32953732 0.28594144 0.16013396 0.21915752 0.38725555
  0.65663039 0.58629947 0.80762084 0.08305085]
 [0.64675487 0.91148306 0.63255951 0.0178501  0.97903966 0.12147638
  0.6494151  0.03939417 0.17670666 0.04161637]
 [0.8516704  0.97965904 0.65231194 0.95323731 0.51715608 0.468906
  0.14091211 0.63995921 0.69986313 0.72660159]
 [0.42955491 0.23721276 0.28469333 0.29969538 0.6450074  0.72890992
  0.35362495 0.49766707 0.27267244 0.00527598]
 [0.30480288 0.2505052  0.78442482 0.74117894 0.10720808 0.83067737
  0.37666489 0.23125332 0.8038596  0.78424481]
 [0.69416609 0.13062192 0.66402345 0.96352557 0.57787396 0.98144647
  0.45443389 0.64670466 0.33767726 0.73323619]
 [0.11669617 0.20177386 0.26005182 0.73839237 0.36860231 0.50696509
  0.26502616 0.41898915 0.16628595 0.46314758]
 [0.29259697 0.22246274 0.25804936 0.63994334 0.60343816 0.21681842
  0.64694641 0.44478909 0.68235414 0.76056063]
 [0.40196397 0.89860108 0.69192281 0.26696745 0.06753528 0.84526352
  0.64089928 0

**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [88]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))

## your code
# вычисляем расстояние от точек Х до у, суммируем расстояния по двум осям для каждой точки X
closestPointIndexes = np.argmin(((X - y)**2).sum(axis=1))
print(y)
print(X[closestPointIndexes])

[[0.55829716 0.73973108]]
[0.3345175  0.60742689]


**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [98]:
## your code
# формируем отдельные иксы для трех промежутков и считаем значение функции на них
x1 = np.linspace(-3, 0, 15)
x2 = np.linspace(0, 2, 10)
x3 = np.linspace(2, 3, 5)
y1 = x1 * x1 + 2 * x1 + 6
y2 = x2 + 6
y3 = x3 * x3 + 4 * x3 - 4
print(y1, y2, y3)

[9.         8.18877551 7.46938776 6.84183673 6.30612245 5.8622449
 5.51020408 5.25       5.08163265 5.00510204 5.02040816 5.12755102
 5.32653061 5.61734694 6.        ] [6.         6.22222222 6.44444444 6.66666667 6.88888889 7.11111111
 7.33333333 7.55555556 7.77777778 8.        ] [ 8.     10.0625 12.25   14.5625 17.    ]


**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [109]:
X = np.random.random((10, 10))

## your code
# из-за погрешности вычислений получаются не ровно нули, но ошибка мала
X = X - np.ones((10, 1)) * X.mean(axis=0)
X.mean(axis=0)

array([ 4.44089210e-17, -6.66133815e-17,  1.44328993e-16,  1.11022302e-17,
       -5.55111512e-17,  4.44089210e-17, -7.77156117e-17,  2.22044605e-17,
       -5.55111512e-17, -8.88178420e-17])

**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [122]:
X = np.random.normal(loc=5, scale=2., size=1000)
print('среднее   ', X.mean())
print('дисперсия ', X.var())


среднее    5.080970472637345
дисперсия  4.224961615577073


**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [135]:
## your code
# сначала создаем матр. со строчками от 0 до 4, затем сдвигаем строчки
matrix = np.array([np.arange(0, 5)]*5)
np.array(list(map(np.roll, matrix, np.arange(0, -5, -1))))

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 0],
       [2, 3, 4, 0, 1],
       [3, 4, 0, 1, 2],
       [4, 0, 1, 2, 3]])

**11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [215]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)    

[0, 3, 4, 0, 4]

Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [222]:
## your code
# используется функция cumsum - прибавляет для каждого следующего элемента массива значение из предыдущего, собственно, происходит то же самое, что и в цикле в вышеописанной функции sample, а дальше значения икс сравниваются со всеми значениями вектора val, затем результаты суммируются, чтобы получить ответ
def sample2(x, c):
    assert len(x) > 0

    s = np.sum(x)
    val = s * np.random.random(c).reshape((c, 1))
    x = np.array(x).cumsum().reshape((1, c))
    res = (x < val)
    return res.sum(axis=1)


sample2([50, 3, 1, 7, 20], 5)

array([0, 0, 3, 0, 4])